services:

  # Servi√ßo do PostgreSQL
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hirepro
    ports:
      - "5432:5432"